[pytest]
filterwarnings =
    ignore::DeprecationWarning

markers =
    unit: fast isolated tests
    component: tests of a single component/class

    logic: tests for game logic
    state: game state and configuration tests
    sound: sound system tests
    arguments: command-line arguments processing tests
    entities: basic entity tests
    theme: theme manager tests
    obstacles: obstacle objects and related manager tests
    assets: assets manager tests

    init: objects initialization tests
    spawn: spawning logic tests
    collision: collision detection tests
    update: objects changes tests
    draw: rendering-related tests
    reset: clearing object states tests

    smoke: ...
    physics: ...